### ISSUE TITLE
Please, specifiy a license

### ISSUE THREAD

**Issue by hlef** [digitalemagine/py-statistics#2]
Hi,

I'd like to package py-statistics for Debian. Unfortunately, this is not possible for the moment because you haven't defined a license for your software.

Regards,
 Hugo

**Comment by stefanocrosta** [comment]
Hello Hugo!

You are right, I did not think about it.

This is mostly an automated conversion of the Py3 source code, so I have freedom over the choice of the licence and I will add the original PSF licence as required.

Do you have any preference on which licence should I use?

I could go with PSF as well, or MIT, or whatever you propose, though I would avoid GPL.

Thanks

Stefano

**Comment by stefanocrosta** [comment]
BTW, currently this is a 2.* backport only, but python statistics is missing as well in py < 3.4

I personally don't like the idea of adding six / future dependencies for such a simple library backport, so I'd rather:

- manually do necessary compatibility tweaks 
- have two statistics py file in here, and a dynamic setup.py to install the correct one
- have two separate packages (py-statistics3 would be the py3<3.4 version)

There does not seem to be synthetic best practices for this - different packages do different things... 

I haven't looked into this in detail yet as I do not use pre 3.4 python - If you don't need it either, I might just skip it.
Otherwise if you have any opinion or preference I'll try and go that way.


Thanks again
Stefano

**Comment by stefanocrosta** [comment]
BTW^2 - i just discovered there's also a "backports.statistics" projecy on pypi/github, which uses the `backports` namespace:
 https://pypi.python.org/pypi/backports.statistics/0.1.0

I have no strong feelings regarding what option is best, but I thought I'd let you know!

**Comment by stefanocrosta** [comment]
Added PSF license  [#6367a160](https://github.com/digitalemagine/py-statistics/commit/4f03a8d5aa7b852412a96219461c4238cc03f58a) and [#4f03a8d5](https://github.com/digitalemagine/py-statistics/commit/4f03a8d5aa7b852412a96219461c4238cc03f58a)

**Comment by hlef** [comment]
Hi Stefano,

Sorry for the very late answer...

Normally, the fact that your backport is not Python 3 compatible shouldn't be a problem (Debian Stretch has 3.5).

Thanks for your work.
 Hugo

**Comment by jakirkham** [comment]
Could we please have the license file added to the `MANIFEST.in`? That way downstream packagers can make sure to include the license in their packages so as to be compliant with the licensing terms.

cc @danring

**Comment by stefanocrosta** [comment]
done!

**Comment by jakirkham** [comment]
Awesome. LGTM. Thanks @stefanocrosta.

**Comment by hlef** [comment]
Thanks ! python-statistics is now available on Debian.

I think we can close the issue now.

**Comment by stefanocrosta** [comment]
Great!!

I'll be here if anything else is needed ;-)

thanks!
