### ISSUE TITLE
Please, provide release tarballs

### ISSUE THREAD

**Issue by hlef** [digitalemagine/py-statistics#3]
Hi,

I'd like to package py-statistics for Debian. It would be very convenient if you could provide release tarballs.

Additionally, you might consider signing your releases. You can find more informations about it [here](https://wiki.debian.org/Creating%20signed%20GitHub%20releases).

Cheers,
 Hugo (hle)

**Comment by stefanocrosta** [comment]
Sure will do shortly!

**Comment by hlef** [comment]
Thanks !

**Comment by stefanocrosta** [comment]
Hello Hugo,

I just added a (signed) first release, but I think I'll shortly update it to the latest (py 3.7.0 alpha 1) because new functions are available in there.

In the meanwhile you might check if the current release is ok. I adopted the release number straight from the original python version I'm using. if that sounds weird or wrong let me know.

Best!
